### ISSUE TITLE
NPE Under Max OS

### ISSUE THREAD

**Issue by iazarny** [iazarny/gitember#9]
Caused by: java.lang.NullPointerException
	at com.az.gitember.service.GitRepoService.getHead(GitRepoService.java:655)
	at com.az.gitember.service.GitRepoService.getBranches(GitRepoService.java:528)
	at com.az.gitember.service.GitRepoService.getBranches(GitRepoService.java:506)
	at com.az.gitember.service.Context.updateBranches(Context.java:224)
	at com.az.gitember.service.Context.init(Context.java:103)
	at com.az.gitember.service.Context.init(Context.java:138)
	at com.az.gitember.controller.Main.openHandler(Main.java:231)

**Comment by iazarny** [comment]
Fixed
